<?xml version="1.0" encoding="utf-8"?><Database Name="QL_NTT" Class="dbQL_NTTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-12J6D6C;Initial Catalog=QL_NTT;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_NTTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table_Admin" Member="Table_Admins">
    <Type Name="Table_Admin">
      <Column Name="ID_ADMIN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOADMIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENADMIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_TK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Table_TaiKhoan_Table_Admin" Member="Table_TaiKhoan" ThisKey="ID_TK" OtherKey="ID_TK" Type="Table_TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_TrungTuyen" Member="Table_TrungTuyens">
    <Type Name="Table_TrungTuyen">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TRUONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TENTOHOP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_CHUYENNGANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MON1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MON2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MON3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TRUNGTUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_ChiTietKhaoSat" Member="Table_ChiTietKhaoSats">
    <Type Name="Table_ChiTietKhaoSat">
      <Column Name="ID_KS" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_HS" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CAUTRALOI" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Table_HocSinh_Table_ChiTietKhaoSat" Member="Table_HocSinh" ThisKey="ID_HS" OtherKey="ID_HS" Type="Table_HocSinh" IsForeignKey="true" />
      <Association Name="Table_KhaoSat_Table_ChiTietKhaoSat" Member="Table_KhaoSat" ThisKey="ID_KS" OtherKey="ID_KS" Type="Table_KhaoSat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_ChuyenNganh" Member="Table_ChuyenNganhs">
    <Type Name="Table_ChuyenNganh">
      <Column Name="ID_CHUYENNGANH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENCHUYENNGANH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_NGANH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MANGANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOHOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Table_ChuyenNganh_Table_CTCN" Member="Table_CTCNs" ThisKey="ID_CHUYENNGANH" OtherKey="ID_CHUYENNGANH" Type="Table_CTCN" />
      <Association Name="Table_ChuyenNganh_Table_GiangVien" Member="Table_GiangViens" ThisKey="ID_CHUYENNGANH" OtherKey="ID_CHUYENNGANH" Type="Table_GiangVien" />
      <Association Name="Table_ChuyenNganh_Table_HocSinh" Member="Table_HocSinhs" ThisKey="ID_CHUYENNGANH" OtherKey="ID_CHUYENNGANH" Type="Table_HocSinh" />
      <Association Name="Table_Nganh_Table_ChuyenNganh" Member="Table_Nganh" ThisKey="ID_NGANH" OtherKey="ID_NGANH" Type="Table_Nganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_CoSo" Member="Table_CoSos">
    <Type Name="Table_CoSo">
      <Column Name="ID_COSO" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCOSO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_CTCN" Member="Table_CTCNs">
    <Type Name="Table_CTCN">
      <Column Name="ID_CTCN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_CHUYENNGANH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Table_ChuyenNganh_Table_CTCN" Member="Table_ChuyenNganh" ThisKey="ID_CHUYENNGANH" OtherKey="ID_CHUYENNGANH" Type="Table_ChuyenNganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_CTKN" Member="Table_CTKNs">
    <Type Name="Table_CTKN">
      <Column Name="ID_CTKN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HINHANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ID_KHOINGHIEP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Table_KhoiNghiep_Table_CTKN" Member="Table_KhoiNghiep" ThisKey="ID_KHOINGHIEP" OtherKey="ID_KHOINGHIEP" Type="Table_KhoiNghiep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_CTN" Member="Table_CTNs">
    <Type Name="Table_CTN">
      <Column Name="ID_CTN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_NGANH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Table_Nganh_Table_CTN" Member="Table_Nganh" ThisKey="ID_NGANH" OtherKey="ID_NGANH" Type="Table_Nganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_CTNC" Member="Table_CTNCs">
    <Type Name="Table_CTNC">
      <Column Name="ID_CTNC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HINHANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ID_NGHIENCUU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Table_NghienCuu_Table_CTNC" Member="Table_NghienCuu" ThisKey="ID_NGHIENCUU" OtherKey="ID_NGHIENCUU" Type="Table_NghienCuu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_CTTTK" Member="Table_CTTTKs">
    <Type Name="Table_CTTTK">
      <Column Name="ID_CTTTK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_THANHTUUKHOA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Table_ThanhTuuKhoa_Table_CTTTK" Member="Table_ThanhTuuKhoa" ThisKey="ID_THANHTUUKHOA" OtherKey="ID_THANHTUUKHOA" Type="Table_ThanhTuuKhoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_CTTTT" Member="Table_CTTTTs">
    <Type Name="Table_CTTTT">
      <Column Name="ID_CTTTT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_THANHTUUTRUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Table_ThanhTuuTruong_Table_CTTTT" Member="Table_ThanhTuuTruong" ThisKey="ID_THANHTUUTRUONG" OtherKey="ID_THANHTUUTRUONG" Type="Table_ThanhTuuTruong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_GiangVien" Member="Table_GiangViens">
    <Type Name="Table_GiangVien">
      <Column Name="ID_GV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOGV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENGV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ID_CHUYENNGANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOCVI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="Table_ChuyenNganh_Table_GiangVien" Member="Table_ChuyenNganh" ThisKey="ID_CHUYENNGANH" OtherKey="ID_CHUYENNGANH" Type="Table_ChuyenNganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_GiangVienDN" Member="Table_GiangVienDNs">
    <Type Name="Table_GiangVienDN">
      <Column Name="ID_GVDN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOGVDN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENGVDN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_NGANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOCVI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Table_Nganh_Table_GiangVienDN" Member="Table_Nganh" ThisKey="ID_NGANH" OtherKey="ID_NGANH" Type="Table_Nganh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_HocBong" Member="Table_HocBongs">
    <Type Name="Table_HocBong">
      <Column Name="ID_HOCBONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENHOCBONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HOCBONG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NAM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_HocSinh" Member="Table_HocSinhs">
    <Type Name="Table_HocSinh">
      <Column Name="ID_HS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTENHS" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TRUONGCAP3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_CHUYENNGANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Table_HocSinh_Table_ChiTietKhaoSat" Member="Table_ChiTietKhaoSats" ThisKey="ID_HS" OtherKey="ID_HS" Type="Table_ChiTietKhaoSat" />
      <Association Name="Table_ChuyenNganh_Table_HocSinh" Member="Table_ChuyenNganh" ThisKey="ID_CHUYENNGANH" OtherKey="ID_CHUYENNGANH" Type="Table_ChuyenNganh" IsForeignKey="true" />
      <Association Name="Table_TaiKhoan_Table_HocSinh" Member="Table_TaiKhoan" ThisKey="ID_TK" OtherKey="ID_TK" Type="Table_TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_KhaoSat" Member="Table_KhaoSats">
    <Type Name="Table_KhaoSat">
      <Column Name="ID_KS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CAUHOI" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_ROOT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Table_KhaoSat_Table_ChiTietKhaoSat" Member="Table_ChiTietKhaoSats" ThisKey="ID_KS" OtherKey="ID_KS" Type="Table_ChiTietKhaoSat" />
    </Type>
  </Table>
  <Table Name="dbo.Table_KhoiNghiep" Member="Table_KhoiNghieps">
    <Type Name="Table_KhoiNghiep">
      <Column Name="ID_KHOINGHIEP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENKHOINGHIEP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Table_KhoiNghiep_Table_CTKN" Member="Table_CTKNs" ThisKey="ID_KHOINGHIEP" OtherKey="ID_KHOINGHIEP" Type="Table_CTKN" />
    </Type>
  </Table>
  <Table Name="dbo.Table_Nganh" Member="Table_Nganhs">
    <Type Name="Table_Nganh">
      <Column Name="ID_NGANH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNGANH" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Table_Nganh_Table_ChuyenNganh" Member="Table_ChuyenNganhs" ThisKey="ID_NGANH" OtherKey="ID_NGANH" Type="Table_ChuyenNganh" />
      <Association Name="Table_Nganh_Table_CTN" Member="Table_CTNs" ThisKey="ID_NGANH" OtherKey="ID_NGANH" Type="Table_CTN" />
      <Association Name="Table_Nganh_Table_GiangVienDN" Member="Table_GiangVienDNs" ThisKey="ID_NGANH" OtherKey="ID_NGANH" Type="Table_GiangVienDN" />
    </Type>
  </Table>
  <Table Name="dbo.Table_NghienCuu" Member="Table_NghienCuus">
    <Type Name="Table_NghienCuu">
      <Column Name="ID_NGHIENCUU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENGHIENCUU" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ANHBIA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Table_NghienCuu_Table_CTNC" Member="Table_CTNCs" ThisKey="ID_NGHIENCUU" OtherKey="ID_NGHIENCUU" Type="Table_CTNC" />
    </Type>
  </Table>
  <Table Name="dbo.Table_NTT" Member="Table_NTTs">
    <Type Name="Table_NTT">
      <Column Name="ID_NTT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNTT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_TaiKhoan" Member="Table_TaiKhoans">
    <Type Name="Table_TaiKhoan">
      <Column Name="ID_TK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ADMIN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Table_TaiKhoan_Table_Admin" Member="Table_Admins" ThisKey="ID_TK" OtherKey="ID_TK" Type="Table_Admin" />
      <Association Name="Table_TaiKhoan_Table_HocSinh" Member="Table_HocSinhs" ThisKey="ID_TK" OtherKey="ID_TK" Type="Table_HocSinh" />
    </Type>
  </Table>
  <Table Name="dbo.Table_ThanhTuuKhoa" Member="Table_ThanhTuuKhoas">
    <Type Name="Table_ThanhTuuKhoa">
      <Column Name="ID_THANHTUUKHOA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTHANHTUUKHOA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Table_ThanhTuuKhoa_Table_CTTTK" Member="Table_CTTTKs" ThisKey="ID_THANHTUUKHOA" OtherKey="ID_THANHTUUKHOA" Type="Table_CTTTK" />
    </Type>
  </Table>
  <Table Name="dbo.Table_ThanhTuuTruong" Member="Table_ThanhTuuTruongs">
    <Type Name="Table_ThanhTuuTruong">
      <Column Name="ID_THANHTUUTRUONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTHANHTUUTRUONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Table_ThanhTuuTruong_Table_CTTTT" Member="Table_CTTTTs" ThisKey="ID_THANHTUUTRUONG" OtherKey="ID_THANHTUUTRUONG" Type="Table_CTTTT" />
    </Type>
  </Table>
  <Table Name="dbo.Table_ToHop" Member="Table_ToHops">
    <Type Name="Table_ToHop">
      <Column Name="IDTOHOP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTOHOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MONTOHOP" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MON1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MON2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MON3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>